cities_descriptions = [
  "Comment ne pas se laisser emporter par le vent de culture et d'art qui règne dans ce quartier touristique de rêve ! Aussi connu comme l'arrondissement du Louvre, il abrite également le jardin des Tuileries, la place Vendôme et la rue Saint-Honoré. Rassurez-vous, vous n'y trouverez cependant pas que des cours d'Art et d'histoire ! Tous les meilleurs cours de loisirs du 1er arrondissement sont sur cette page.",
  "Aussi connu comme l'arrondissement de la Bourse - en tout cas pour son siège historique, le 2e est le plus petit arrondissement de Paris. L'Opéra Comique et la célèbre rue de la Paix y ont élu domicile : vous êtes entre de bonnes mains ! Tous les meilleurs cours de loisirs du 2e arrondissement sont sur cette page.",
  "Anciennement appelé l'arrondissement du Temple pour son fameux marché couvert le Carreau du Temple, aujourd'hui le 3e arrondissement est surtout connu pour son quartier festif à la mode : le Marais. Profitez de son ambiance et de son ouverture d'esprit avec tous les meilleurs cours de loisirs du 3e arrondissement sur cette page.",
  "La réputation culturelle et architecturale du 4e arrondissement n'est plus à faire ! De Notre Dame de Paris sur l'île de la Cité aux célèbres escalators du musée d'Art Contemporain de M. Pompidou en passant par la place de l'Hôtel de Ville, vous avez beaucoup de choses à admirer sur le chemin de votre cours de loisirs ! Tous les meilleurs cours de loisirs du 4e arrondissement sont sur cette page.",
  "Le 5e arrondissement de Paris est une vrai joyau historique de notre capitale. Ses frontières se confondent presque avec celles du quartier latin. Plus ancien quartier de Paris, les constructions romaines de la ville antique Lutèce s'étendaient de l'actuelle rue du Val-de-Grâce jusqu'à la rue du Pot-de-Ferses. Que vous visitiez les grands hommes du Panthéon ou les érudits de la Sorbonne, vous êtes sûr d'en sortir grandi ! Tous les meilleurs de loisirs du 5e arrondissement sont sur cette page.",
  "Venez vous divertir, vous défouler ou simplement profiter du temps qui passe dans le chicissime 6e arrondissement de Paris. Des élégants cafés de St Germain bercés par les rythmes jazzys au plus festif quartier de l'Odéon, vous ne risquez pas de vous ennuyer. Tous les meilleurs de loisirs du 6e arrondissement sont sur cette page.",
  "Prestigieux arrondissement au Nord de la Tour Eiffel, le 7e n'abrite pas que les plus beaux appartements de la capitale. Il est également le quartier de nombreux ministères, de l'Assemblée Nationale, de l'Hôtel Matignon et de l'UNESCO. Nulle besoin d'être si sérieux ! venez décompresser avec tous les cours de loisirs du 7e arrondissement sur cette page.",
  "Aux Champs Élysées, padapadapa…. Venez céder au rêve de la capitale de la mode dans le 8e arrondissement. De la Place de la Concorde à l'Arc de Triomphe, vous trouverez vraiment tous les meilleurs de loisirs du 8e arrondissement grâce à cette page.",
  "C'est au 19e siècle que le 9e arrondissement de Paris connu ses heures de gloire, lorsque l'élite intellectuelle et artistique de Paris y installa ses plus beaux appartements. Aussi connu comme l'arrondissement au coeur du mouvement romantique de Paris, vous serez subjugué par la beauté de l'Opéra Garnier et de la musique qui l'habite. Vous aussi, venez développer tout votre potentiel grâce aux meilleurs cours de loisirs du 9e arrondissement sont sur cette page.",
  "Venez flâner le long du Canal St Martin pour profiter de toutes ses saveurs cosmopolites. Mais ne vous contentez pas d'y manger ! Tous les meilleurs cours de loisirs du 10e arrondissement sont sur cette page.",
  "Aujourd'hui plus célèbre pour son ambiance festive que pour ses attraits touristiques, saviez-vous que le 11e arrondissement était à l'époque au cœur du Paris révolutionnaire et des luttes de classe ? Connu pour la place de la Bastille et les bars de la rue Oberkampf, venez vous épanouir au rythme de tous les meilleurs cours de loisirs du 11e arrondissementqui sont sur cette page.",
  "De la gare de Lyon jusqu'au bout du Bois de Vincennes, le 12e arrondissement tel qu'on le connaît est un héritage napoléonien bucolique très prisé par les Parisiens quand il fait beau. Mais en été comme en hiver, vous trouverez tous les meilleurs cours de loisirs du 12e arrondissement sur cette page.",
  "Son cœur a beau être italien, le 13e arrondissement est surtout connu pour les apports culturels et gastronomiques de son quartier asiatique. Ne ratez pas la butte aux Cailles et la Bibliotèque Nationale de France qui y a élu domicile depuis 1990. Tous les meilleurs cours de loisirs du 13e arrondissement sont sur cette page.",
  "Les Catacombes, les ateliers d'artistes, les théâtres, les crêperies et tout ce qui fait du 14e arrondissement un grand village avec sa culture propre. Centre artistique historique de Paris, le 14e arrondissement brille encore de toutes ses couleurs le dimanche matin lors de son marché hebdomadaire d'Art. Mais vous trouverez également de nombreux cours de sport et de bien-être dans le 14e arrondissement. Tous les meilleurs cours de loisirs du 14e arrondissement sont sur cette page.",
  "Arrondissement le plus peuplé de Paris, le 15e est essentiellement résidentiel et charme pour son côté \"petit ville à lui seul\". Bien plus vaste et riche que pour sa seule rue du Commerce, venez profitez de tous les meilleurs cours de loisirs du 15e arrondissement sur cette page.",
  "Plus vaste arrondissement de Paris, le 16e arrondissement est aussi connu pour ses nombreux musées comme le Palais de Tokyo et le musée Galliera. Les sportifs aussi sont gâtés avec l'Hippodrome de Longchamp et le Parc des Princes pour ne citer que les plus célèbres. Vous aussi, rejoignez les meilleurs cours de loisirs du 16e arrondissement sur cette page.",
  "Ne vous fiez pas aux façades haussmanniennes imposantesaux abords du parc Monceau, le 17e arrondissement offre une vie de quartier de plus en plus riche ! Peut-être est-ce l'héritage laissé par Marcel Pagnol rue de Fortuny, tout le monde se presse dans le 17e et Ternes et les Batignolles n'en sont que les exemples les plus connus. Rejoignez le mouvement, tous les meilleurs cours de loisirs du 17e arrondissement sont sur cette page.",
  "Surplombé par la superbe cathédrale du Sacré Cœur, aucun quartier n'offre de balades plus romantiques que le 18e arrondissement. Un pied dans le passé bohème de Montmartre et un autre dans le futur au marché de Barbès. Vous trouverez forcément de quoi vous divertir. Tous les meilleurs cours de loisirs du 18e arrondissement sont sur cette page.",
  "Le superbe parc des Buttes Chaumont donne à ce quartier très éclectique un côté bucolique. Ses terrasses et ses prairies sont une ère de relaxation très prisée des Parisiens l'été. Ne manquez pas la modernisation du 19e arrondissement de Paris et choisissez parmi les meilleurs cours de loisirs du 19e arrondissement sur cette page.",
  "À l'intersection des quartiers de Belleville, de Ménilmontant et de Père Lachaise, le 20e arrondissement est rempli de petits ateliers d'artistes et de rues gorgées d'histoire. Anciennement connu pour son passé industriel, aujourd'hui l'arrondissement retravaille son image et a beaucoup de choses à vous offrir. Tous les meilleurs cours de loisirs du 20e arrondissement sont sur cette page."
]

paris = City.find('paris')
(1..20).each do |index|
  city = City.find("paris-#{(index < 10 ? "0#{index}" : index)}")
  city.update_column :parent_city_id, paris.id
  city.update_column :description, cities_descriptions[index + 1]
end
neighborhood = City::Neighborhood.create(name: "La Chappelle / Porte de la Chappelle" , city_id: City.find('paris-18').id, latitude: 48.894190, longitude: 2.364013, remote_image_url: "https://upload.wikimedia.org/wikipedia/commons/f/fd/P1060171_Paris_XVIII_rue_de_la_Chapelle_rwk.jpg")
neighborhood.description = "Situé tout à fait au Nord de Paris intramuros, le très coloré marché de l'Olive éclaire quotidiennement le quartier populaire de la Chapelle. Passez par la place Paul Eluard en son centre et rejoignez l'Église Saint-Denys de la Chapelle pour faire un bond dans le Moyen-Âge et capter toute la complexité de ce quartier en pleine modernisation. Ou sinon, prenez un des meilleurs cours de loisirs du quartier sur cette page !"
neighborhood.save
neighborhood = City::Neighborhood.create(name: "La Goutte D'or"                       , city_id: City.find('paris-18').id, latitude: 48.888733, longitude: 2.355587, remote_image_url: "http://www.guideapolis.fr/resources/MEDIA_ROOT/MEDIA_ROOT/T1280819105838.jpg")
neighborhood.description = "A l'Est de la Butte Montmartre et doté d'une superbe vue du Sacré Cœur, le quartier de la Goutte d'or garde son côté parisien typique et un charme populaire enviable. Suivez un des meilleurs cours de loisirs de votre quartier sur cette page !"
neighborhood.save
neighborhood = City::Neighborhood.create(name: "Clignancourt / Portes de Clignancourt", city_id: City.find('paris-18').id, latitude: 48.892518, longitude: 2.344326, remote_image_url: "https://upload.wikimedia.org/wikipedia/commons/d/df/MetrodeParisPorteDeClignancourt_(1).JPG")
neighborhood.description = "Sur le versant Nord de l'ancien Montmartre, profitez de cette vie de quartier à l'ancienne et flânez dans ses rues aux immeubles anciens. De nombreux centres sportifs et centres artistiques et culturels de Clignancourt vous accueilleront, il ne vous reste plus qu'à choisir parmi les meilleurs cours de loisirs de votre quartier sur cette page."
neighborhood.save
neighborhood = City::Neighborhood.create(name: "Buttes Chaumont / Place des fêtes"    , city_id: City.find('paris-19').id, latitude: 48.878507, longitude: 2.381776, remote_image_url: "http://www.mickaelarcos.fr/photos/2007-12-23-ButtesChaumont/P1020900.jpg")
neighborhood.description = "Aussi branché que populaire, ce quartier du nord-est de Paris a tout pour vous plaire. Profitez des espaces verts des Buttes Chaumont pour faire un jogging, méditer ou encore suivre un des meilleurs cours de loisirs mis en place par notre équipe sur cette page."
neighborhood.save
neighborhood = City::Neighborhood.create(name: "Canal Saint-Martin / Ourcq / Villette", city_id: City.find('paris-19').id, latitude: 48.886855, longitude: 2.385749, remote_image_url: "https://upload.wikimedia.org/wikipedia/commons/d/d2/Paris_Canal_St-Martin_%C3%A9cluses_R%C3%A9collets_2013.jpg")
neighborhood.description = "Entre l'ambiance calme et romantique du canal et l'effervescence de la Villette, tout est réuni pour un cadre de vie de qualité. Prenez le temps de suivre un des meilleurs cours de loisirs de votre quartier sur cette page."
neighborhood.save
neighborhood = City::Neighborhood.create(name: "Bel-Air"                              , city_id: City.find('paris-12').id, latitude: 48.841833, longitude: 2.405318, remote_image_url: "https://upload.wikimedia.org/wikipedia/commons/9/95/P1000443_Paris_XII_Avenue_du_Bel_Air_reductwk.JPG")
neighborhood.description = "De la barrière du Trône au Bois de Vincennes, Bel-Air vit au rythme des commerces de l'avenue Daumesnil. C'est un quartier résidentiel agréable et prisé des Parisiens intramuros l'été. Pourtant à Bel-Air, nul besoin d'être un prince pour profiter des meilleurs cours de loisirs de votre quartier ! Choisissez celui qu'il vous faut sur cette page."
neighborhood.save
neighborhood = City::Neighborhood.create(name: "Javel / Balard"                       , city_id: City.find('paris-15').id, latitude: 48.839926, longitude: 2.278560, remote_image_url: "https://c1.staticflickr.com/9/8345/8205415303_2a6ee4ece9_b.jpg")
neighborhood.description = "Le quartier est plus connu pour ses sièges sociaux que pour son joli parc et ses quais et c'est bien dommage. Promenez-vous le long de la Seine et profitez d'une vue enviable et méconnue de la Tour Eiffel. Les meilleurs cours de loisirs de votre quartier sont sur cette page."
neighborhood.save
neighborhood = City::Neighborhood.create(name: "Chaillot / Arc de Triomphe"           , city_id: City.find('paris-16').id, latitude: 48.869862, longitude: 2.292197, remote_image_url: "http://www.bankingtech.com/files/2014/07/Arc_de_Triomphe_Place_Charles_de_Gaulle_Paris-Paris-France-arc-de-triomphe.jpg")
neighborhood.description = "L'Arc de Triomphe a été achevé en 1836, le Palais du Trocadéro est un héritage de l'Exposition Universelle de 1878 qui se tenait sur le Champ de Mars. Des monuments historiques impressionants ! Aujourd'hui encore, vous pouvez être surpris : retrouvez les meilleurs cours de loisirs de votre quartier sur cette page."
neighborhood.save
neighborhood = City::Neighborhood.create(name: "Batignolles"                          , city_id: City.find('paris-17').id, latitude: 48.888298, longitude: 2.314768, remote_image_url: "http://www.pariswebtvquartier.fr/images/historique/6tv-batignolles.jpg")
neighborhood.description = "Paul Verlaine a choisi de se reposer pour toujours dans ce petit village pris en étau entre le chic 17e et la plus festive Place de Clichy, et ce n'est pas pour rien ! Entre le marché bio, son joli square et ses restaurants bobos, les Batignolles ont beaucoup à offrir. Laissez-vous tenter par un des meilleurs cours de loisirs de votre quartier sur cette page."
neighborhood.save
neighborhood = City::Neighborhood.create(name: "Barbes / Rochechouart"                , city_id: City.find('paris-09').id, latitude: 48.883760, longitude: 2.349508, remote_image_url: "http://static.panoramio.com/photos/original/46752686.jpg")
neighborhood.description = "C'est la révolution à Barbès ! Un quartier déjà en ébullition pris d'assaut par des designers et des restaurateurs de haut vol. Ne ratez pas ce virage et choisissez parmi les meilleurs cours de loisirs de votre quartier sur cette page."
neighborhood.save
neighborhood = City::Neighborhood.create(name: "Arts et Metiers"                      , city_id: City.find('paris-03').id, latitude: 48.866665, longitude: 2.357270, remote_image_url: "http://1.bp.blogspot.com/-HU5pOswfvs0/U24gE9Khh_I/AAAAAAAARag/UIJyeXGzeqU/s1600/statue+de+la+libert%C3%A9+mus%C3%A9e+des+arts+et+m%C3%A9tiers+paris+4+8.JPG")
neighborhood.description = "Tout petit quartier à côté du marché des Enfants Rouges, il est d'abord connu pour le Conservatoire National des Arts et Métiers. Souvent on ignore que la rue au Maire est le plus ancien quartier chinois de Paris. Mais vous ne trouverez pas que des cours de langues ici ! Tous les meilleurs cours de loisirs de votre quartier sont sur cette page."
neighborhood.save
neighborhood = City::Neighborhood.create(name: "Père Lachaise"                        , city_id: City.find('paris-20').id, latitude: 48.852400, longitude: 2.303651, remote_image_url: "https://myfavoritelist.files.wordpress.com/2012/06/pere01.jpg")
neighborhood.description = "Laissez Honoré de Balzac, Frédéric Chopin, Oscar Wilde, et tous les autres se reposer dans l'un des cimetières les plus célèbres au monde et prenez part à l'un des meilleurs cours de loisirs de votre quartier sur cette page. Vous serez peut-être inspirés par leur talent !"
neighborhood.save
neighborhood = City::Neighborhood.create(name: "Invalides / École militaire"          , city_id: City.find('paris-07').id, latitude: 48.853915, longitude: 2.310342, remote_image_url: "https://upload.wikimedia.org/wikipedia/commons/5/54/Paris_-_Les_invalides_-_Le_D%C3%B4me_-_139.jpg")
neighborhood.description = "Quartier complexe qui abrite à la fois le musée de l'Armée, le tombeau de Napoléon, le musée de Rodin et le musée d'Orsay. Ne vous y méprenez pas, rien ne vaut une balade le long de ses espaces verts. Rejoignez les équipes de foot et de rugby qui les peuplent l'été ou bien choisissez parmi les meilleurs cours de loisirs de votre quartier sur cette page."
neighborhood.save
neighborhood = City::Neighborhood.create(name: "Denfert Rochereau"                    , city_id: City.find('paris-14').id, latitude: 48.833864, longitude: 2.332615, remote_image_url: "https://upload.wikimedia.org/wikipedia/commons/b/bc/P1150548_Paris_XIV_place_Denfert-Rochereau_rwk.jpg")
neighborhood.description = "Quel plaisir de se balader sur la rue Daguerre et rencontrer des commerçants hauts en couleurs… Mais le quartier ne s'arrête pas à cette rue mythique : prenez un des meilleurs cours de loisirs de votre quartier sur cette page et vous en sortirez aussi fier que la réplique en bronze du Lion de Belfort !"
neighborhood.save
neighborhood = City::Neighborhood.create(name: "Montparnasse / Gaïté"                 , city_id: City.find('paris-14').id, latitude: 48.837273, longitude: 2.335387, remote_image_url: "https://upload.wikimedia.org/wikipedia/commons/thumb/3/35/Cimetiere_Montparnasse_Paris_Genie_Daillion.jpg/1280px-Cimetiere_Montparnasse_Paris_Genie_Daillion.jpg")
neighborhood.description = "Ce quartier du nord du 14e arrondissement de Paris est un repère historique d'artistes qui, comme Gainsbourg, ont parfois décidé d'y reposer à jamais.Faites un bond de la tour Montparnasse jusque dans  les meilleurs cours de loisirs de votre quartier sur cette page."
neighborhood.save
neighborhood = City::Neighborhood.create(name: "Place de Clichy / Pigalle"            , city_id: City.find('paris-09').id, latitude: 48.883646, longitude: 2.333144, remote_image_url: "https://upload.wikimedia.org/wikipedia/commons/6/6e/P1040791_Paris_VIII-IX-XVII-XVIII_place_de_Clichy_rwk.jpg")
neighborhood.description = "Quartier festif prisé pour ses bars à cocktails et autres bars branchés, de la Place de Clichy jusqu'à Pigalle vous trouverez toujours de quoi vous mettre dans l'ambiance ! En attendant la nuit, piochez parmi les meilleurs cours de loisirs de votre quartier sur cette page."
neighborhood.save
neighborhood = City::Neighborhood.create(name: "Canal Saint-Martin / Gare de l'est"   , city_id: City.find('paris-10').id, latitude: 48.875069, longitude: 2.361836, remote_image_url: "https://upload.wikimedia.org/wikipedia/commons/8/8c/Paris-Gare_de_l'Est-2009.jpg")
neighborhood.description = "Au sud du canal de Saint-Martin, le soleil brille encore plus fort et la vie le long des quais ne trouve jamais de fin. Prenez part à cette ambiance bucolique en réservant un des meilleurs cours de loisirs de votre quartier sur cette page."
neighborhood.save
neighborhood = City::Neighborhood.create(name: "Strasbourg-Saint-Denis"               , city_id: City.find('paris-10').id, latitude: 48.869424, longitude: 2.354255, remote_image_url: "http://4.bp.blogspot.com/-R7koUJhIp1g/U80v9DNyhmI/AAAAAAAAWzk/wnLYdOw9gLo/s1600/Paris+Tu%CC%88rk+Mahallesi+Strasbourg+Saint-Denis+2.jpg")
neighborhood.description = "Comment passer à côté de la richesse culturelle de ce quartier de l'est de Paris ? Les théâtres s'enchainent sur le boulevard et les nombreux bars festifs invitent le badaud à se détendre après un moment de rigolade, de réflexion ou simplement de plaisir. Pour bousculer le rythme de votre journée, suivez un des meilleurs cours de loisirs de votre quartier sur cette page."
neighborhood.save
neighborhood = City::Neighborhood.create(name: "Bastille"                             , city_id: City.find('paris-11').id, latitude: 48.853078, longitude: 2.369550, remote_image_url: "https://upload.wikimedia.org/wikipedia/commons/4/4b/P1160484_Paris_IV-XI-XII_place_de_la_Bastille_rwk.jpg")
neighborhood.description = "La Bastille n'y est plus depuis le 15 juillet 1789, mais le quartier est toujours aussi vivant ! Si vous n'êtes pas d'humeur à assister à un opéra ou à flâner dans ses rues animées, prenez un des meilleurs cours de loisirs de votre quartier sur cette page."
neighborhood.save
neighborhood = City::Neighborhood.create(name: "Odéon / Quartier latin"               , city_id: City.find('paris-06').id, latitude: 48.852115, longitude: 2.340260, remote_image_url: "https://upload.wikimedia.org/wikipedia/commons/6/60/Th%C3%A9%C3%A2tre_de_l'Od%C3%A9on,_Paris_6e_140402_1.jpg")
neighborhood.description = "Quartier le plus ancien de Paris, les touristes affluent par millions pour visiter ses ruines antiques, la sublime place Saint Michel ou encore l'université mythique de la Sorbonne.Pour vous trouver un petit coin de tranquillité ou encore rencontrer de nouvelles personnes, n'hésitez plus, réservez un des meilleurs cours de loisirs de votre quartier sur cette page."
neighborhood.save
neighborhood = City::Neighborhood.create(name: "Marais / Beaubourg"                   , city_id: City.find('paris-04').id, latitude: 48.859935, longitude: 2.360738, remote_image_url: "http://leblow.co.uk/wp-content/uploads/2012/12/Centre-Beaubourg.jpg")
neighborhood.description = "Aussi branché que joyeux, les charmes du Marais attirent des touristes des 4 coins du monde comme les parisiens les plus anciens pour l'ambiance de ses nuits ou pour ses attraits culturels. Choisissez parmi les meilleurs cours de loisirs de votre quartier sur cette page."
neighborhood.save
neighborhood = City::Neighborhood.create(name: "Belleville / Ménilmontant"            , city_id: City.find('paris-20').id, latitude: 48.872818, longitude: 2.389461, remote_image_url: "http://images.neverendingvoyage.com/wp-content/uploads/2013/09/belleville_paris-9.jpg")
neighborhood.description = "Un des quartiers les plus créatifs et vivants de Paris, ne ratez pas la rue Doyez et ses graffitis pour bien vous imprégner de son esprit artistique. Vous pouvez aller plus loin, rencontrer des gens et profiter des meilleurs cours de loisirs de votre quartier sur cette page."
neighborhood.save
neighborhood = City::Neighborhood.create(name: "République / Oberkampf"               , city_id: City.find('paris-03').id, latitude: 48.867503, longitude: 2.363811, remote_image_url: "http://stephanekirkland.com/wp-content/uploads/2012/01/IMG_0896.jpg")
neighborhood.description = "Quartier incontournable des fêtards parisiens, vous pouvez y apprécier de la musique de tous styles du plus populaire au plus sélect. La vie culturelle et les théâtres y sont nombreux. Pas moyen de s'ennuyer ! Tout ça sans compter les meilleurs cours de loisirs de votre quartier que vous pouvez réserver sur cette page."
neighborhood.save
neighborhood = City::Neighborhood.create(name: "Grands Boulevards / Opéra"            , city_id: City.find('paris-09').id, latitude: 48.870871, longitude: 2.332217, remote_image_url: "https://upload.wikimedia.org/wikipedia/commons/d/dc/Paris_Opera_full_frontal_architecture,_May_2009.jpg")
neighborhood.description = "Ne vous laissez pas impressionner par le superbe Opéra Garnier et les luxueuses boutiques qui l'entourent, ce quartier offre des options très variées pour tous. Les Grands Boulevards accueillent souvent des fêtards de tous bords du lundi au dimanche, dans une franche camaraderie. Rejoignez le mouvement et suivez un des meilleurs cours de loisirs de votre quartier sur cette page."
neighborhood.save
neighborhood = City::Neighborhood.create(name: "Butte-aux-Cailles / Place d'Italie"   , city_id: City.find('paris-13').id, latitude: 48.827191, longitude: 2.349080, remote_image_url: "https://upload.wikimedia.org/wikipedia/commons/3/3a/Paris_13e_Cinq-Diamants_Butte-aux-Cailles_1.JPG")
neighborhood.description = "Des charmants cafés et bars de la petite colline de la Butte-aux-Cailles jusqu'à la dynamique Place d'Italie, ce quartier du 13e a un charme de bourgade en plein Paris. Profitez des meilleurs cours de loisirs de votre quartier sur cette page."
neighborhood.save
neighborhood = City::Neighborhood.create(name: "Bercy"                                , city_id: City.find('paris-12').id, latitude: 48.835455, longitude: 2.385683, remote_image_url: "http://www.vhavocats.fr/data/img1385388783.jpg")
neighborhood.description = "Il n'y a pas que le Ministère de l'Économie, des Finances et de l'Industrie et Bercy Village qui compte au Nord-Est de la Seine ! Trouvez les meilleurs cours de loisirs de votre quartier sur cette page."
neighborhood.save
neighborhood = City::Neighborhood.create(name: "Montmartre"                           , city_id: City.find('paris-18').id, latitude: 48.886715, longitude: 2.338890, remote_image_url: "http://www.euroscope.fr/images/produits/big/186/sacra_copy__coeur_07.jpg")
neighborhood.description = "C'est probablement le quartier le plus touristique de Paris, mais c'est également l'un des plus charmants ! Comment ne pas s'émouvoir devant le superbe Sacré Cœur et les jolies rues anciennes qu'il surplombe ? Vous pourriez aussi profiter de la vue en essayant un des meilleurs cours de loisirs que nous avons rassemblés pour vous sur cette page."
neighborhood.save
neighborhood = City::Neighborhood.create(name: "Gare de Lyon"                         , city_id: City.find('paris-12').id, latitude: 48.844325, longitude: 2.374338, remote_image_url: "https://upload.wikimedia.org/wikipedia/commons/a/ae/Gare_de_Lyon_Paris.JPG")
neighborhood.description = "Pas besoin de prendre un train direction le Sud ou de manger au célèbre Train Bleu pour vous évader dans le 12e. Choisissez parmi les meilleurs cours de loisirs de votre quartier sur cette page pour vous divertir, vous épanouir, vous défouler et beaucoup plus !"
neighborhood.save
neighborhood = City::Neighborhood.create(name: "Nation"                               , city_id: City.find('paris-11').id, latitude: 48.848747, longitude: 2.394907, remote_image_url: "http://static.panoramio.com/photos/large/43003219.jpg")
neighborhood.description = "Venez faire un tour à la place de la Nation : depuis le départ de la guillotine vous ne risquez plus d'y perdre la tête ! Quartier parisien méconnu, il est pourtant doté de commerces dynamiques et de cafés agréables. Prenez le temps de le découvrir en suivant un des meilleurs cours de loisirs de votre quartier sur cette page."
neighborhood.save
