development:
  host: localhost
  adapter: postgresql
  encoding: unicode
  database: coursavenue_development
  pool: 5
  username: postgres
  password: password

test:
  host: localhost
  adapter: postgresql
  encoding: unicode
  database: coursavenue_test
  pool: 5
  username: postgres
  password: password

production:
  host: ec2-54-228-219-94.eu-west-1.compute.amazonaws.com
  adapter: postgresql
  encoding: unicode
  database: d28s2bum2hoqh7
  pool: 5
  username: qjppevpnykjrmw
  password: v8HdyVB0F-ZJrgsgz7ApBBrrap
