development:
  host: localhost
  adapter: postgresql
  encoding: unicode
  database: leboncours_development
  pool: 5
  username: postgres
  password: password

test:
  host: localhost
  adapter: postgresql
  encoding: unicode
  database: leboncours_test
  pool: 5
  username: postgres
  password: password

production:
  host: localhost
  adapter: postgresql
  encoding: unicode
  database: leboncours_production
  pool: 5
  username: admin
  password: password
