development:
  host: localhost
  adapter: postgresql
  encoding: unicode
  database: leboncours_development
  pool: 5
  username: postgres
  password: password

test:
  host: localhost
  adapter: postgresql
  encoding: unicode
  database: leboncours_test
  pool: 5
  username: postgres
  password: password

production:
  host: ec2-54-243-238-218.compute-1.amazonaws.com
  adapter: postgresql
  encoding: unicode
  database: df2kmto67m9fb3
  pool: 5
  username: eypgvyrdvljjjb
  password: JTIq4AjygHjDALZPJz7O4Z87yW
