#!/bin/bash -e
# https://gist.github.com/aliou/80f4a7977a29109d0ebc
# TODO: Store app_name (coursavenue, coursavenue-staging) in env.
# TODO: Store staging deploy term (staging:deploy) in env.

APP_NAME=$1

# Fetch the last commits on the remote.
git remote add heroku git@heroku.com:$APP_NAME.git
git fetch heroku

# Check if the deploy is necessary.
#
# The deploy is necessary when:
# - We push a branch with the term 'staging:deploy' somewhere in the commits, or
# - We push the branch master in production.
STAGING_DEPLOY=$(git log heroku/master..HEAD | grep 'staging:deploy' | wc -l)
if [[ $APP_NAME == "coursavenue-staging" ]] && [ $STAGING_DEPLOY -eq 0 ]; then
  exit
fi

# Check if the deploy requires a migration.
REQUIRES_MIGRATION=$(git diff HEAD heroku/master --name-only -- db | wc -l)

# Deploy the code. (This might take a while, up to 30 minutes.)
echo "[CIRCLECI_DEPLOY] Deploying code."
if [[ $APP_NAME == "coursavenue-staging" ]]; then
  git push heroku $CIRCLE_SHA1:master -f
else
  git push heroku $CIRCLE_SHA1:master
fi

# Run migrations if needed.
if [ $REQUIRES_MIGRATION -gt 0 ]; then
  echo "[CIRCLECI_DEPLOY] Running migration."
  heroku run rake db:migrate -a $APP_NAME
fi
